# Q3
*Work with Numpy*<br>
In this notebook you're going to work with the numpy library to solve the problems<br>
Please follow the instructions and hints provided for each cell

## Part A

In [6]:
import numpy as np
import random

In [7]:
def create_matrix(n):
  """
  In this function you should create matrix in order of n*n with random numbers 
  in the [n, n+100) interval.

  see the bellow link:
    https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

  Arguments:
    inputs:
      n: an integer describing the order of the matrix
    outputs:
      created matrix  
  """
  ##############################################
  ############ YOUR CODES GO HERE ##############
  
  matrix = np.random.randint(n, n+100, size=(n, n))
  ##############################################

  return matrix

In [8]:
"""
In this cell you should get the input n and create the matrix by calling the function
Then print the matrix
"""
##############################################
############ YOUR CODES GO HERE ##############
n = int(input("Enter the order of the matrix: "))
matrix = create_matrix(n)
# print matrix
print(matrix)
##############################################

[[ 94  41  47  57  78  71]
 [100  97  47  53  41   7]
 [ 49  90  46  13  65  34]
 [ 62  15  80  50  38  44]
 [103   8  63  85  78  83]
 [ 40  43  95  51  81  99]]


In [9]:
def count_digits(matrix):
  """
  In this function you should implement a routine to count the digits in the given matrix.

  Arguments:
    inputs:
      matrix: input matrix
    outputs:
      digits: a dictionary containing digits as its keys and the counted numbers as its value
  """

  ##############################################
  ############ YOUR CODES GO HERE ##############
  
  digits = {}
  for i in range(10):
    digits[i] = 0
  for i in range(len(matrix)):
    for j in range(len(matrix)):
      strdeg= str(matrix[i][j])
      for k in range(len(strdeg)):
        digits[int(strdeg[k])] += 1
   
  ##############################################

  return digits


In [10]:
"""
In this cell call the implemented function and print the result
"""


def printres(res):
  for i in range(10):
    print("Digit {} : {}".format(i, res[i]))
res = count_digits(matrix)
printres(res)
##############################################
############ YOUR CODES GO HERE ##############  
##############################################

Digit 0 : 7
Digit 1 : 9
Digit 2 : 1
Digit 3 : 8
Digit 4 : 12
Digit 5 : 8
Digit 6 : 4
Digit 7 : 8
Digit 8 : 8
Digit 9 : 7


## Part B

In [11]:
def traverse_matrix(matrix):
    """
    Traverse the input matrix in the given manner then print result

    Arguments:
      inputs:
        matrix: input matrix
      outputs
    """
    x = [0, 0]
    n = len(matrix)
    result = []
    result.append(x)
    goside = 1
    goDiameter = 0
    lastlocation = x
    s=0
    d=0
    while (lastlocation != [n-1, n-1]):
        lastlocation = result[len(result)-1].copy()
        if goside == 1:
            if lastlocation[0]==0 and lastlocation[1]==n-1:
                lastlocation[0]+=1
                s=1
            elif lastlocation[0]==0 or lastlocation[0]==n-1 and lastlocation!=(n-1,n-1) :
                
                
                lastlocation[1]+=1
                s=1
            elif lastlocation[1]==n-1 or lastlocation[1]==0 and lastlocation!=(0,0) and lastlocation!=(n-1,n-1):
                lastlocation[0]+=1
                s=1
                
                
        elif goDiameter == 1:
            m=lastlocation.copy()
            temp = lastlocation[0]
            lastlocation[0] = lastlocation[1]
            lastlocation[1] = temp
            i=[-1,-1]
            if m[0]<lastlocation[0] :
                i[0]*=-1
            if m[1]<lastlocation[1] :
                i[1]*=-1
            while m!=lastlocation :
                b=0
                m[0]+=i[0]
                m[1]+=i[1]
                
                result.append(m.copy())
                
                
                
            d=1
        if d==1:
            goside=1
            goDiameter=0
            d=0
        elif s==1:
            goside=0
            goDiameter=1
            s=0
        
        if result[len(result)-1]!=lastlocation:
            result.append(lastlocation.copy())
        lastlocation = result[len(result)-1]
        res=[]
    # for e in result:
    #     if res.__contains__(e):
    #         pass
    #     else:
    #         res.append(e)
    return result


In [12]:
res=traverse_matrix(matrix)
print(res)

[[0, 0], [0, 1], [1, 0], [2, 0], [1, 1], [0, 2], [0, 3], [1, 2], [2, 1], [3, 0], [4, 0], [3, 1], [2, 2], [1, 3], [0, 4], [0, 5], [1, 4], [2, 3], [3, 2], [4, 1], [5, 0], [5, 1], [4, 2], [3, 3], [2, 4], [1, 5], [2, 5], [3, 4], [4, 3], [5, 2], [5, 3], [4, 4], [3, 5], [4, 5], [5, 4], [5, 5]]
