# Q4

## Part A

In [24]:
import numpy as np

"""
Please define the mentioned matrices and the operations

consider the bellow links:
https://numpy.org/doc/stable/reference/generated/numpy.transpose.html

https://numpy.org/doc/stable/reference/generated/numpy.dot.html

"""

##############################################
############ YOUR CODES GO HERE ##############  


a=np.array([[1,2,3],[4,5,6],[7,8,9]])

b=np.array([[1,2,3],[4,5,6],[7,8,9]])
c=np.array([[1],[-1],[1]])

newtranspose=np.transpose(a)
# print(newtranspose)
res=np.dot(newtranspose,a)

# print(res)
reverse=np.linalg.inv(res)
res2=np.dot(reverse,newtranspose)
res3=np.dot(res2,c)
final=np.add(res3,a)
print(final)


##############################################

[[0.796875 1.796875 2.796875]
 [4.       5.       6.      ]
 [7.203125 8.203125 9.203125]]


## Part B

In [36]:
def window_sliding(A, B):

  """
  In this function you should implement the sliding window method

  Arguments:
    inputs:
      A: a matrix of 3*3 order for treating as the window
      B: a matrix of 5*5 order for treating as the input matrix
    outputs:
      res: resulting matrix of the sliding window 
  """

  ##############################################
  ############ YOUR CODES GO HERE ##############
  n=A.shape[0]
  m=B.shape[0]
  res=np.zeros((n-m+1,n-m+1))
  for i in range(0,n-m+1):
    for j in range(0,n-m+1):
      res[i,j]=np.multiply(A[i:i+m , j:j+m], B).sum()

  ##############################################

  return res

In [38]:
A = np.array([[1,1,1,1,1],[1,2,2,2,1],[1,2,2,2,1],[1,2,2,2,1],[1,1,1,1,1]])
B = np.array([[1,1,1],[1,-9,1],[1,1,1]])
print(window_sliding(A, B))

[[-7. -5. -7.]
 [-5. -2. -5.]
 [-7. -5. -7.]]
